POST http://localhost:15672/api/exchanges/%2f/amq.default/publish
Content-Type: application/json
Authorization: Basic YW5hbHl0aWNzX3NlcnZpY2U6cGFzc3dvcmQ=

{
  "properties": {
    "content-type": "application/json"
  },
  "routing_key": "imported-vacancies-queue",
  "payload":  "test message",
  "payload_encoding": "string"
}