spring:
  rabbitmq:
    port: 5672

  data:
    mongodb:
      port: 27017
      database: vacancies_db
      auto-index-creation: true

rabbitmq:
  queue:
    consumer:
      name: imported-vacancies-queue
    producer:
      name: new-vacancies-queue
