spring:
  rabbitmq:
    host: rabbitmq
    username: analytics_service
    password: ${RABBIT_PASSWORD}

  data:
    mongodb:
      host: vacancies-db
      username: analytics_service
      password: ${MONGODB_PASSWORD}